version: '3'

services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181      

  kafka: # broker server
    container_name: "kafka"
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper    
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092      
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # KAFKA_CREATE_TOPICS: "test:1:1" # Topic명:Partition개수:Replica개수

networks:
  default:
    external:
      name: cozy-kafka