
server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://localhost:8761/eureka

spring :
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**

        - id : my-second-name
          uri: lb://MY-SECOND-NAME
          predicates:
            - Path=/my-second-name/**

      default-filters:
        - name : GlobalFilter
          args:
            baseMessage : Spring Gateway Global Filter
            preLogger : true
            postLogger : true

